name: Basic validation

on:
  pull_request:
    paths-ignore:
      - '**.md'
  push:
    branches:
      - main
      - releases/*
    paths-ignore:
      - '**.md'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  call-basic-validation:
    name: Basic validation
    uses: actions/reusable-workflows/.github/workflows/basic-validation.yml@main

  test-action-plugins: # make sure the action works on a clean machine
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          helm-plugins: >
            https://github.com/databus23/helm-diff,
            https://github.com/jkroepke/helm-secrets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  test-action-auto-init: # make sure the action works on a clean machine
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          helmfile-auto-init: 'true'
          helm-plugins: >
            https://github.com/databus23/helm-diff,
            https://github.com/jkroepke/helm-secrets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
